// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4JphBtr5H8raWvqSLaHzB9pWkd4XuHI',
    appId: '1:1030457040174:web:ef61597615f6164d66eebf',
    messagingSenderId: '1030457040174',
    projectId: 'memomemo-a4659',
    authDomain: 'memomemo-a4659.firebaseapp.com',
    storageBucket: 'memomemo-a4659.firebasestorage.app',
    measurementId: 'G-ENZ8QTH92Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAok2sCL-SoI_8wc4-L4jl22WJeU2q3_S0',
    appId: '1:1030457040174:android:4266d93490b66f4166eebf',
    messagingSenderId: '1030457040174',
    projectId: 'memomemo-a4659',
    storageBucket: 'memomemo-a4659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXRlfVblBsQl368awCeWrdX22nm-9wz8',
    appId: '1:1030457040174:ios:6f581061c3ec673566eebf',
    messagingSenderId: '1030457040174',
    projectId: 'memomemo-a4659',
    storageBucket: 'memomemo-a4659.firebasestorage.app',
    iosBundleId: 'com.example.memomemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXRlfVblBsQl368awCeWrdX22nm-9wz8',
    appId: '1:1030457040174:ios:6f581061c3ec673566eebf',
    messagingSenderId: '1030457040174',
    projectId: 'memomemo-a4659',
    storageBucket: 'memomemo-a4659.firebasestorage.app',
    iosBundleId: 'com.example.memomemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm4JphBtr5H8raWvqSLaHzB9pWkd4XuHI',
    appId: '1:1030457040174:web:9c1a1889d72f24b466eebf',
    messagingSenderId: '1030457040174',
    projectId: 'memomemo-a4659',
    authDomain: 'memomemo-a4659.firebaseapp.com',
    storageBucket: 'memomemo-a4659.firebasestorage.app',
    measurementId: 'G-PPKV4VNWNL',
  );
}
